Mbarba/brc mode
Ensembl/ensembl-genomio pull request #180
Opened 2023-10-31 10:41 UTC by MatBarba

Clean up brc_mode usage:

- define as 0 by default in all pipelines
- remove from scripts where it is not used
- use params.brc_mode universally
- add some basic pipeline tests

2023-10-31 10:58 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/dumper_pipeline/main.nf
> +        --brc_mode	                   Override Ensembl 'species' and 'division' with the corresponding BRC4 ones ('organism_abbrev' and 'component')
```suggestion
        --brc_mode	               Override Ensembl 'species' and 'division' with the corresponding BRC4 ones ('organism_abbrev' and 'component')
```

2023-11-01 14:43 UTC, JAlvarezJarreta requested changes
Looks great, couple of minor changes.

Two comments (not affecting the approval in any way):
* I fear how this is going to be merged with PR#173 (there are places that have been changed in both)
* I'm wondering if there is something similar than the parametrize in pytest for the Nextflow tests to avoid reflecting information such as `_brc_mode_of` in the name...

2023-11-01 14:43 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/additional_seq_prepare/main.nf
> +        --brc_mode                     Set to 1 to use with BRC data (default: ${paranms.brc_mode})
```suggestion
        --brc_mode                     Set to 1 to use with BRC data (default: ${params.brc_mode})
```

2023-11-01 14:53 UTC, MatBarba commented
> Looks great, couple of minor changes.
> 
> Two comments (not affecting the approval in any way):
> 
>     * I fear how this is going to be merged with PR#173 (there are places that have been changed in both)
Rebase/merges make it pretty easy to resolve conflicts along the way. We just need to make sure that the tests work in the end.
> 
>     * I'm wondering if there is something similar than the parametrize in pytest for the Nextflow tests to avoid reflecting information such as `_brc_mode_of` in the name...
Some of the files contents should actually differ, so we do need that distinction. I don't intend to add other variations though.

2023-11-02 12:34 UTC, JAlvarezJarreta approved these changes

2023-11-02 13:02 UTC, merged