Disha/update func anno
Ensembl/ensembl-genomio pull request #305
Opened 2024-03-04 17:56 UTC by Dishalodha

This PR is to add xrefs to functional_annotation.json file as the current code only adds synonyms and uses default dbname (BRC4_Community_Annotation) to load all the xrefs which is incorrect.
I have added an xrefs array for transcripts and translations using provider_name as dbname and name. 

Vasily and I also found a bug in loading load_fann.pl file where the external_dbs were loaded as dictionary and not an array of dict causing the same db_name to overwrite even though the pattern is different in the config file (config/external_db_map/default.txt)

2024-03-05 12:23 UTC, vsitnik approved these changes
Thank you!

2024-03-05 17:41 UTC, JAlvarezJarreta requested changes
Some minor changes to avoid introducing unintended changes or empty spaces where they should not be.

2024-03-07 18:26 UTC, MatBarba approved these changes

2024-03-08 16:27 UTC, JAlvarezJarreta approved these changes

2024-03-08 16:27 UTC, JAlvarezJarreta commented on src/python/ensembl/io/genomio/gff3/extract_annotation.py
> +import logging
```suggestion

import logging
```

2024-03-08 16:31 UTC, merged