Disha/hack feb/update tests genbank
Ensembl/ensembl-genomio pull request #321
Opened 2024-03-13 21:34 UTC by Dishalodha

Here I have created unit testing for extract_data from the genbank module
I have divided the tests into 2 files:

- test_extract_data.py : Tests all the methods that generate a output file
- test_extract_data_seq.py: Tests all the internal methods and formatting of the files

2024-03-14 12:00 UTC, JAlvarezJarreta reviewed
_Partial review_

2024-03-14 12:00 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data.py
> +from Bio.SeqFeature import SeqFeature, FeatureLocation
```suggestion

from BCBio import GFF
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.SeqFeature import SeqFeature, FeatureLocation
import pytest
```

2024-03-14 12:00 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +from Bio.SeqRecord import SeqRecord
```suggestion
from typing import List
from unittest.mock import Mock, patch

from Bio.SeqRecord import SeqRecord
```

2024-03-14 12:00 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +
```suggestion
```

2024-03-21 17:17 UTC, JAlvarezJarreta requested changes
A few things to review to make the code more homogeneous. On top of the comments made, a couple of general ones:
* It would be nice if `@patch`, `@dependencies` and `@parametrize` where all in the same order in all the tests (that is not the case now)
* I believe `formatted_files_generator` fixture can be move into a `conftest.py` file located in `src/python/tests/genome_metadata`, so every test inside can access it. Alternatively, you can create the object by default once for every test [example](https://github.com/Ensembl/ensembl-compara/blob/release/111/src/python/tests/test_repair_mlss_tags.py#L46-L56) and take advantage of having all tests within a Test class.

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        record.features = [gene_feature, rna_feature, CDS_feature]
```suggestion
        cds_feature = SeqFeature(
            FeatureLocation(10, 20), type="CDS", qualifiers={gene_name: "GlyrA", "transl_table": "2"}
        )
        record.features = [gene_feature, rna_feature, cds_feature]
```

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        assert gene_feature.qualifiers[gene_name] == expected_name
```suggestion
```
This is testing behaviour of biopython (that's on them to do, not us).

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        """Raises error then there is unspported feature"""
```suggestion
        """Tests parsing records with unsupported features."""
```

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        formatted_files_generator: FormattedFilesGenerator,
Same as above.

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        rna_name: str,
Sames as before.

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        gene_id: str,
Same as before.

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        self, expected_location: str, formatted_files_generator, organelle: str
```suggestion
        self, formatted_files_generator: FormattedFilesGenerator, expected_location: str, organelle: str
```

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        assert str(exc_info.value) == f"Unknown organelle: {organelle}"
```suggestion
        with pytest.raises(UnsupportedData, match=f"Unknown organelle: {organelle}"):
            # pylint: disable=protected-access
            formatted_files_generator._prepare_location(organelle)
```

2024-03-21 17:17 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +        self, expected_value: str, formatted_files_generator: FormattedFilesGenerator, type_feature: str
Same as before.

2024-04-18 16:08 UTC, Dishalodha commented on src/python/ensembl/io/genomio/genbank/extract_data.py
> +    parser = ArgumentParser(description=__doc__)
okay yes sure

2024-04-23 14:24 UTC, Dishalodha commented on src/python/ensembl/io/genomio/genbank/extract_data.py
> +    parser = ArgumentParser(description="Parse a GenBank file and create cleaned up files from it.")
I am not sure, the module's docstring is a complete explaination of what we expect in this module and maybe its better to keep that?

2024-04-23 15:12 UTC, JAlvarezJarreta approved these changes
I'm happy with the current status of this code :+1:

2024-04-25 11:07 UTC, JAlvarezJarreta approved these changes
Couple of minor changes, but the code is good to go!

2024-04-25 11:07 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data.py
> +from pytest import TempPathFactory
```suggestion
```

2024-04-25 11:07 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data.py
> +import pytest
```suggestion
import pytest
from pytest import TempPathFactory
```

2024-04-25 11:07 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +from pytest import TempPathFactory
```suggestion
```

2024-04-25 11:07 UTC, JAlvarezJarreta commented on src/python/tests/genbank/test_extract_data_seq.py
> +import pytest
```suggestion
import pytest
from pytest import TempPathFactory
```

2024-04-25 13:01 UTC, merged