Mbarba/test seqregion dump
Ensembl/ensembl-genomio pull request #420
Opened 2024-08-14 10:24 UTC by MatBarba

- Move `external_db` code from the `seq_region` dump module to their own module (and subfolder `external_db/`)
- Use iterators to get coord_system and seq_regions in dumper (clearer, easier to use and test): `fetch_coord_systems`, `fetch_seq_regions`
- Add tests for the `external_db` module + `seq_region` dump module

Coverage should be 100% with both sqlite and mysql testing.

2024-08-15 16:07 UTC, ens-LCampbell requested changes
Mostly minor edits/suggestions

2024-08-15 16:07 UTC, ens-LCampbell requested changes
Mostly minor edits/suggestions

2024-08-15 17:01 UTC, JAlvarezJarreta requested changes
Quite a nice refactoring + updates. A few minor elements require attention, but overall it looks very good :+1:

2024-08-15 17:01 UTC, JAlvarezJarreta commented on src/python/tests/seq_region/test_dump.py
> +        param({"toplevel": 1, "codon_table": 2}, {"codon_table": 2}, id="With codon table"),
```suggestion
        param({"toplevel": 1, "codon_table": 2}, {"codon_table": 2}, id="with codon table"),
```
You are not using capital case in the other IDs.

2024-08-15 17:01 UTC, JAlvarezJarreta commented on src/python/tests/seq_region/test_dump.py
> +        param({"toplevel": 1, "sequence_location": "chr"}, {"location": "chr"}, id="Location"),
```suggestion
        param({"toplevel": 1, "sequence_location": "chr"}, {"location": "chr"}, id="location"),
```

2024-08-20 14:35 UTC, MatBarba commented on src/python/ensembl/io/genomio/seq_region/dump.py
> +        seqr: SeqRegion = row[0]
Just `seq_region` since that's how we call them in the database/API.

2024-08-20 14:35 UTC, MatBarba commented on src/python/ensembl/io/genomio/seq_region/dump.py
> +        attrib_dict: The attribs for this seq_region.
ok

2024-09-09 15:20 UTC, merged